version: '3.8'

networks:
  crawler:
    name: crawler
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      # 配置文件
      - ./redis/conf:/redis/config:rw
      # 数据文件
      - ./redis/data/:/redis/data:rw
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    restart: always
    networks:
      - crawler
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: crawler/mysql:8.3.0
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - crawler
  zhihu_crawler:
    container_name: zhihu_crawler
    image: zhaoweilong007/zhihu_crawler:1.0
    volumes:
      - ./config/crawler.yml:/app/resources/crawler.yml
      - ./config/db.setting:/app/resources/db.setting
    restart: always
    networks:
      - crawler