name: schedule

on:
  workflow_dispatch:
  schedule:
    # 每天12点更新 按照UTC时间计算
    - cron: "0 4 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump env context
        run: echo '${{ toJSON(env) }}'
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - name: Execute Gradle build
        run: ./gradlew build run
      - name: 归档爬取数据
        uses: EndBug/add-and-commit@v9
        with:
          message: update by github action
          committer_name: zhaoweilong
          committer_email: zhaoweilong176@gmail.com

